version: 0.2

env:
  variables:
    DOCKERHUB_USERNAME: "sk22tp"
    DOCKERHUB_PASS: "wingardian"

phases:
  pre_build:
    commands:
      - echo pre_build step...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t python-image:3.9 .    
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker tag python-image:3.9 414399442808.dkr.ecr.eu-west-1.amazonaws.com/python-image:3.9
      - aws ecr get-login-password --region eu-west-1 --profile sonal | docker login --username AWS --password-stdin 414399442808.dkr.ecr.eu-west-1.amazonaws.com
      - docker push 414399442808.dkr.ecr.eu-west-1.amazonaws.com/python-image:3.9 
